alias e='$EDITOR'
alias ll='ls -alF'
alias la='ls -A'
alias ...='cd ..'
alias fucking='sudo'
alias please='sudo'
alias todo='e ~/todo.md'
alias webshare='python -m SimpleHTTPServer' # opens web server of current dir on port 8000
alias gimme='ps aux|grep'
alias ff='find . -iname'
alias ccat='pygmentize -g -O style=colorful,linenos=1'
